name: Rust Checks

on:
  push:

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Check formatting
        run: |
          cargo +nightly fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Cache Rust registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/git
            !~/.cargo/git/checkouts
            ~/.cargo/registry
            !~/.cargo/registry/src
          key: rust-registry-${{hashFiles('**/Cargo.lock') }}

      - name: Clippy
        run: |
          cargo clippy \
            --workspace \
            --locked \
            --no-deps \
            --profile test \
            -- \
            -D warnings

      - name: Show sccache stats
        if: always()
        run: sccache --show-stats

  cargo-test:
    name: Cargo Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
      - name: Cache Rust registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/git
            !~/.cargo/git/checkouts
            ~/.cargo/registry
            !~/.cargo/registry/src
          key: rust-registry-${{hashFiles('**/Cargo.lock') }}

      - name: Cargo Test
        run: |
          cargo test \
            --workspace \
            --locked \
            --profile test \
            --all-targets \
            --no-fail-fast

      - name: Show sccache stats
        if: always()
        run: sccache --show-stats
